version: "3.5"

services:
  web-server-nginx:
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../fpm-be/static:/etc/nginx/static
      - ../fpm-be/media:/etc/nginx/media
      - ../fpm-fe-html/:/usr/share/nginx
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - fpm-project-network
    depends_on:
      - fpm-data-api
  fpm-data-api:
    image: fpm-data-api
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - MONGO_HOST=db-mongodb
    networks:
      - fpm-project-network
    depends_on:
      - db-mongodb
  db-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/cnf:/etc/mongo
      - ./mongodb/log:/var/log/mongodb
    entrypoint: ["mongod", "-f", "/etc/mongo/mongod.conf"]
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - fpm-project-network 
    restart: always

networks:
  fpm-project-network:
    driver: bridge

